package-lock.json
src/components/views/Header.js
src/components/views/Login.js
src/styles/_theme.scss
src/styles/index.scss
src/styles/views/Game.scss
src/styles/views/Header.scss
src/styles/views/Login.scss
src/styles/views/Registration.scss

Design Login (and some changes on Register)

41 do design for login page joe

---

src/components/views/Registration.js
src/styles/views/Login.scss
src/styles/views/Registration.scss

Adjusted Design for Register Page (Mainly CSS)

-Adjusted Design for Register Page

---

src/components/views/Header.js
src/components/views/Login.js
src/styles/views/Login.scss

same procedure as I have already done for register.. I will try to find a solution for the moving login button after Joe's Pull request has been accepted

added errormessage if username or password is not valid

---

src/components/routing/routers/AppRouter.js
src/components/views/EditUserPage.js
src/components/views/Header.js
src/components/views/UserPage.js
src/helpers/api.js
src/styles/views/Header.scss
src/styles/views/Registration.scss
src/styles/views/UserPage.scss

Branch has wrong name. IS 44_users_can_access_their_account_and_view_info.
Everything up to date and should be working

44_users_can_access_their_account_and_view_info

---

src/components/views/BlackCardSelection.js
src/components/views/Header.js
src/components/views/Login.js
src/components/views/Registration.js
src/components/views/UserPage.js
src/styles/ui/BaseContainer.scss
src/styles/views/UserPage.scss

It doesn't look nice yet, the design is something somebody should do later

27 the card which was chosen is displayed in the users profile for the next hours

---

src/components/views/BlackCardSelection.js
src/components/views/Header.js
src/components/views/UserPage.js
src/helpers/api.js

Intermediate Bug Fix, will fix it nicely soon, but it should work now

82 successfull registration throws error but still logs in

---

src/components/views/BlackCardSelection.js
src/components/views/Header.js
src/components/views/Registration.js
src/components/views/UserPage.js
src/helpers/api.js

94 logging in the user status is not changed to online

---

src/components/routing/routers/AppRouter.js
src/components/views/EditUserPage.js
src/components/views/Header.js
src/components/views/Registration.js
src/components/views/UserPage.js
src/styles/views/UserPage.scss

User should be able to change username and gender
No design yet
Added .trim to edit and register page to stop users using same name with spaces

20 by clicking on an edit button in the user account page the user is able to change his personal data

---

src/components/views/EditUserPage.js

Addition of "Delete Account" button on the Edit Page.
Asks for Confirmation when deleting account.
Delete Account method redirects to Login Page

45 add delete button to edit page

---

src/components/views/UserPage.js
src/styles/views/UserPage.scss

Very minor Changes, only Design +
Changes on "dummy Userpage" used while loading (just deleted "username" etc as placeholders)

22_Design for User Account

---

src/components/views/BlackCardSelection.js
src/components/views/PlayWhites.js
src/components/views/UserPage.js
src/models/Game.js

The user can choose a blackcard. The black card is shown in the users profil page.
Problem with routing -> i opened new issue

26 users can choose one of the black cards client

---

src/components/views/BlackCardSelection.js
src/components/views/PlayWhites.js
src/components/views/UserPage.js
src/models/Game.js

play white cards:
- you can choose white cards on a black card
- a play gets post
There ar emore than 8 cards??

17 the 8 white cards are visible to the user

---

src/components/views/EditUserPage.js
src/components/views/Registration.js

-very small PR, just the design for the react-select component (The only real change is that in the selector when choosing the options are all visible and not just empty until you hoover over them)

-Added Styling for the react-select component

---

src/components/views/PlayWhites.js

When 404 Error with error message: "There is no black card of another user left" is thrown by server, no error is thrown by the client.
Instead a black card is shown with the text: No black card available

79 when there is no blackcard left of another user a text must be shown for the user who is playing

---

src/components/views/UserPage.js
src/styles/_theme.scss
src/styles/ui/CardButton.scss
src/styles/views/UserPage.scss

Only Design Changes and very minor ones
Moving the blackcard/chooseblack card on userscreen to center. 
Changing disabled black cards to not have opacity
Adding a title
Introduced "fontsizesmall, -medium &-large" in theme.scss to make font sizes more consistent.

25 redesign userprofile with black card choosen for the day

---

src/components/routing/routers/GameRouter.js
src/components/views/GameMenu.js
src/components/views/Matches.js
src/components/views/Registration.js

!!! IMPORTANT !!!
-> merge PR/MR #117 from branch #115 on the server FIRST! this branch depends on that.
implement page where matched users are displayed,
if there are matches, then they are displayed as cardButtons with some info about them

26 matches view

---

README.md
src/components/views/Login.js
src/components/views/PlayWhites.js

Bugfix routing without black card

---

src/components/views/Registration.js
src/components/views/UserPage.js
src/styles/_theme.scss
src/styles/ui/Button.scss
src/styles/views/LoginRegistration.scss
src/styles/views/UserPage.scss

Same as PR that was accidentaly merged into master

73 make sure the different pages of the website are similar in style

---

src/components/views/UserPage.js

finding build error?

---

package-lock.json
package.json
src/components/ui/Avatar.js
src/components/ui/ChatListItem.js
src/components/ui/MatchListItem.js
src/components/views/Matches.js
src/styles/views/Matches.scss

matchside with styling
Functon to chat and userpage not working at the moment

123 create css for matchchat overview

---

src/components/views/Login.js

might soon be irrelevant.. but here it is for completeness..

add demo user button is below login button

---

src/components/views/BlackCardSelection.js

IMPORTANT: The server was also chanched (GameController and userService)
see other pr

147 if user already choose a black card he can not choose one instead the choosen one is presented

---

src/components/views/EditUserPreferencePage.js
src/components/views/UserPage.js
src/styles/_theme.scss
src/styles/views/GameMenu.scss

-Please merge at the same time as 201 (Backend for passing the maxRange)
There are parameters distance and maxRange as distance referes to the value of the rangesliders position and maxRange to the assigned range value of this position

156 user can select preference for maximum distance of userprofiles (blackcards) presented to him

---

src/components/ui/CardButton.js
src/components/ui/CardContainer.js
src/components/ui/ViewTitle.js
src/components/views/BlackCardSelection.js
src/components/views/Matches.js
src/components/views/PlayWhites.js
src/components/views/RateWhites.js
src/styles/index.scss
src/styles/ui/CardButton.scss
src/styles/ui/CardContainer.scss
src/styles/ui/MenuContainer.scss
src/styles/views/Matches.scss

Styling of Cards:
scrollable if text is to long
fontsize changed, to fit titel of page
fontsize of titel (h1) changed
Marging changed, that it is the same on all views
width and height of all cards changed

Styling of cards

---

src/components/views/RateWhites.js

bugfix: games get deleted when inactive and no plays left

Bugfix deleting game when inactive and no plays

---

src/components/ui/MatchListItems.js

Add Custom Avatar for every user

---

src/components/views/Login.js
src/components/views/Registration.js

======================== IMPORTANT ======================
- merge PR for branch 159_geolocation_api on the server first.
- location can't be determined when run on localhost, so this needs to be merged to the master soon, to check if it works

163 geolocation api

---

src/components/ui/MatchListItems.js
src/components/views/Chat.js
src/components/views/Registration.js
src/styles/_theme.scss
src/styles/ui/DatePicker.scss
src/styles/views/Chat.scss
src/styles/views/Matches.scss
src/styles/views/UserHand.scss

closes #173 
Adapt: DatePicker, Header of Chat, Don't rerender ChatItems every second, Hand.

Adapt chat header and datepicker

---

src/components/ui/CardButton.js
src/components/views/GameMenu.js
src/components/views/Sidebar.js

a proposed change to the style of the menu
also i added some missing buttons

add icons to menu cards

---

src/components/views/BlackCardSelection.js
src/components/views/EditUserPage.js
src/components/views/UserHand.js
src/styles/views/LoginRegistration.scss
src/styles/views/UserHand.scss
src/styles/views/UserPage.scss

and minor change to align things in EditPage

button width scales with changing window size

---

src/components/views/Chat.js

@serainaschraff This was the issue from monday where I unmatched you while you were in the chat

Handle 404 error by returning to match overview

---

src/components/views/Login.js
src/components/views/Registration.js
src/components/views/UserPage.js
src/styles/views/UserPage.scss

@TwoDigitsOneNumber Now the geolocation works...
@anhuwi Some quick maffs for the zoom of the map (zoom uses log2)

Improve code

---

package-lock.json
package.json
src/components/views/Login.js
src/components/views/Registration.js
src/components/views/UserPage.js
src/styles/views/UserPage.scss

ATENTION: server change needed as well (get longitude and latitude from user)
add Map to userProfile

add map to userProfile with maxRange
